defaults: &defaults
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:
    
development:
  database: fb_bbclistenlive
  <<: *defaults

production:
  database: fb_bbclistenlive
  <<: *defaults
  
test:
  database: fb_bbclistenlive_test
  <<: *defaults